filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /tmp/cluster-logs/*.log
    harvester_buffer_size: 100
    multiline:
      pattern: '^\['
      negate: false
      match: before
#output.elasticsearch:
#  hosts: ["http://cluster-elasticsearch:9200"]
#  index: "cluster-filebeat-%{+yyyy.MM.dd}"
output.logstash:
  hosts: ["cluster-logstash:5044"]
  index: "cluster-filebeat"
  ssl:
    enabled: false
setup.template:
  name: "cluster-filebeat"
  pattern: "cluster-filebeat-*"